### ISSUE TITLE
supervisorctl error: unix:///var/run/supervisor.sock no such file

### ISSUE THREAD

**Issue by dwdixon** [sfinlon/cif-docker#1]
I think this is related to specifying a config file for supervisord with ```-c```...if we renamed supervisord.conf to cif.conf and moved the location of of our cif specific supervisord config to ```/etc/supervisor/conf.d/``` I believe this error may just go away as it will then pull in the default supervisord.conf parameters that are needed to eliminate this issue.  If so, we probably also would no longer need to specify a config using ```-c``` as the default supervisord.conf should pull in everything in ```/etc/supervisor/conf.d/```.  At worst we may just need to use ```-c``` to tell it to use the default config at  ```/etc/supervisor/supervisord.conf```.

**Comment by sfinlon** [comment]
this is the way docker functions, it runs a command on entry, if it fails just restart the container don't worry aobut trying to manually start anything up
